version: 2.1

orbs:
  github-maven-deploy: github-maven-deploy/github-maven-deploy@1.2.0

mvn-deploy-command: &mvn-deploy-command
  mvn-deploy-command: mvn -s settings/settings.xml clean deploy -DskipTests -Dcheckstyle.skip -B -Prelease
#  context: RELEASE_PROFILE_BBOTTEMA

workflows:
  workflow:
    jobs:
      - github-maven-deploy/approve-deploy-patch-version:
          type: approval
      - github-maven-deploy/approve-deploy-minor-version:
          type: approval
      - github-maven-deploy/approve-deploy-major-version:
          type: approval
      - github-maven-deploy/deploy-patch-version:
          requires:
            - github-maven-deploy/approve-deploy-patch-version
          <<: *mvn-deploy-command
      - github-maven-deploy/deploy-minor-version:
          requires:
            - github-maven-deploy/approve-deploy-minor-version
          <<: *mvn-deploy-command
      - github-maven-deploy/deploy-major-version:
          requires:
            - github-maven-deploy/approve-deploy-major-version
          <<: *mvn-deploy-command