version: 2.1

orbs:
  maven-deploy: wasiqb/maven-deploy@2.0.3

workflows:
  workflow:
    jobs:
      - maven-deploy/code-checkout
      - maven-deploy/build:
          command: mvn clean install -DskipTests -Dcheckstyle.skip
          requires:
            - maven-deploy/code-checkout
          filters:
            branches:
              only:
                - master
                - release
                - /issue-.*/
      - maven-deploy/deploy:
          mentions: mfaisalkhatri,wbhamla1
          fail_only: false
          filters:
            branches:
              only:
                - master
          requires:
            - maven-deploy/build
          deploy-command: mvn deploy --settings .circleci/settings.xml -DskipTests -Dcheckstyle.skip -B -Prelease
          context: RELEASE_PROFILE_WASIQB
