version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:11-jdk-stretch

jobs:

  build-and-test:
    executor: maven-executor

    steps:
      - checkout
      - restore_cache:
          key: coteafs-parent-{{ checksum ".circleci/config.yml" }}
      - run:
          command: mvn clean install -DskipTests -Dcheckstyle.skip
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run:
          shell: /bin/bash -eo pipefail -O globstar
          command: |
            cp **/target/*.pom artifacts/
      - store_artifacts:
          path: artifacts

workflows:
  workflow:
    jobs:
      - build-and-test