version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:11-jdk-stretch

jobs:
  working_directory: ~/repo

  build-and-test:
    executor: maven-executor

    steps:
      - checkout
      - run:
          command: mvn clean install -DskipTests -Dcheckstyle.skip

workflows:
  workflow:
    jobs:
      - build-and-test