version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:11-jdk-stretch

jobs:
  working_directory: ~/repo

  build-and-test:
    executor: maven-executor

    steps:
      - checkout
      - run:
          command: mvn clean install -DskipTests -Dcheckstyle.skip

  deploy-patch-version:
    executor: maven-executor
    steps:
      - run:
          command: ""

  deploy-minor-version:
    executor: maven-executor
    steps:
      - run:
          command: ""

  deploy-major-version:
    executor: maven-executor
    steps:
      - run:
          command: ""

workflows:
  workflow:
    jobs:
      - build-and-test
      - approve-patch-version:
          type: approval
          requires:
            - build-and-test
      - approve-minor-version:
          type: approval
          requires:
            - build-and-test
      - approve-major-version:
          type: approval
          requires:
            - build-and-test
      - deploy-patch-version:
          requires:
            - approve-patch-version
      - deploy-minor-version:
          requires:
            - approve-minor-version
      - deploy-major-version:
          requires:
            - approve-major-version