name: Artifacts deployment to Maven Central

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type: major, minor, patch'
        required: true
        default: 'minor'

env:
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  validate-input:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.release_type == 'patch' }}
    steps:
      - name: Release Type selected for making release
        run: echo "[${{ github.event.inputs.release_type }}] release in progress."

  prepare-release-patch-snapshot:
    needs:
      - validate-input
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.release_type == 'patch' }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Restore local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Maven command to update Patch snapshot version
        run: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit

      - name: Build the artifacts
        run: mvn clean install -DskipTests -Dcheckstyle.skip

      - name: Upload target folder
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: |
            ${{ github.workspace }}/target
            ${{ github.workspace }}/pom.xml

  release-patch-snapshot:
    runs-on: ubuntu-latest
    needs:
      - prepare-release-patch-snapshot
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Restore local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Download target folder
        uses: actions/download-artifact@v2
        with:
          name: target

      - name: Release patch snapshot to Maven central
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          maven_profiles: release
          server_id: ossrh
          maven_args: --settings ${{ github.workspace }}/setting/settings.xml -DskipTests -Dcheckstyle.skip -B

  prepare-release-patch:
    needs:
      - release-patch-snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Restore local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Download target folder
        uses: actions/download-artifact@v2
        with:
          name: target

      - name: Maven command to update Patch version
        run: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion} versions:commit

      - name: Build the project
        run: mvn clean install -DskipTests -Dcheckstyle.skip

      - name: Upload target folder
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: |
            ${{ github.workspace }}/target
            ${{ github.workspace }}/pom.xml

  release-patch:
    runs-on: ubuntu-latest
    needs:
      - prepare-release-patch
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Restore local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}

      - name: Download target folder
        uses: actions/download-artifact@v2
        with:
          name: target

      - name: Release patch to Maven central
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          maven_profiles: release
          server_id: ossrh
          maven_args: --settings ${{ github.workspace }}/setting/settings.xml -DskipTests -Dcheckstyle.skip -B

  push-pom:
    runs-on: ubuntu-latest
    needs:
      - release-major
      - release-minor
      - release-patch
    outputs:
      release-version: ${{ steps.artifacts.outputs.version }}
    if: always()
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Download target folder
        uses: actions/download-artifact@v2
        with:
          name: target

      - name: Get the release version
        id: artifacts
        run: |
          MVN_VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "::set-output name=version::$MVN_VERSION"

      - name: Push updated pom.xml
        uses: EndBug/add-and-commit@v7
        with:
          add: pom.xml
          message: Released v-$MVN_VERSION to Maven central
          default_author: github_actions
          push: true

  push-tag:
    runs-on: ubuntu-latest
    needs:
      - push-pom
    steps:
      - name: Download target folder
        uses: actions/download-artifact@v2
        with:
          name: target

      - name: Push updated pom.xml
        uses: EndBug/add-and-commit@v7
        with:
          tag: v${{ needs.push-pom.outputs.release-version }}
          message: Released to Maven central
          default_author: github_actions
          signoff: true
          push: true

  github-release:
    runs-on: ubuntu-latest
    needs:
      - push-pom
      - push-tag
    steps:
      - name: Download target folder
        uses: actions/download-artifact@v2
        with:
          name: target

      - name: Create GitHub Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ needs.push-pom.outputs.release-version }}
          title: Version ${{ needs.push-pom.outputs.release-version }}
          prerelease: false
          files: |
            target/*.jar
            target/*.pom